builds:
  - binary: forward
    main: ./cmd/forward/main.go
    goos:
      - windows
      - darwin
      - linux
      - openbsd
      - freebsd
      - netbsd
    goarch:
      - amd64
      - arm
      - arm64
      - 386
      - mips64
      - mips64le
      - riscv64
    goarm:
      - 6
      - 7
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
      - -trimpath

archives:
  - files:
      - none*
    name_template: "forward_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
